"""
weather_lookup
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "ashok.gopichander@lseg.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-11-18", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "ashok.gopichander@lseg.com": "mailto:ashok.gopichander@lseg.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm3n6auxt1ael01pktite7b1e/cloud-ide/cm3n7lxlp1ap801pkyt1jgflc/cm3n7nqnd1as501o6wer97tp5",
    },
)
def weather_lookup():

dag_obj = weather_lookup()
